### ISSUE TITLE
Limit error message size when marking a job as failed

### ISSUE THREAD

**Issue by oleschoenburg** [camunda/connector-sdk#345] opened 2023-01-17 11:01 UTC
__Is your feature request related to a problem? Please describe.__

During development, trying out different FEEL output expressions, failure to evaluate the expression can lead to _very large_ exception messages. This is because the error message includes the full stack trace but also the "context". If we think of the HTTP connector, that context includes the HTTP response which can be of arbitrary size.

Zeebe has a `maxMessageSize` limit, by default 4 MiB. Everything that exceeds that limit can't be written by Zeebe. In the case of `FailJob` gRPC requests, this means that jobs are _not_ marked as failed. 

This is a **bad experience for the user** because they get no feedback that indicates that evaluating the FEEL expression failed and only see a process stuck at handling the connector job.

__Describe the solution you'd like__

The connector SDK should limit the length of the supplied error message to something reasonable. For the user, getting a truncated stack trace as preferable over having no feedback that an error occurred.

https://github.com/camunda/connector-sdk/blob/main/runtime-util/src/main/java/io/camunda/connector/runtime/util/outbound/ConnectorJobHandler.java#L127-L129

would be a good place to introduce such a limit.

__Describe alternatives you've considered__

Solve this in Zeebe. There are [many](https://github.com/camunda/zeebe/issues/10963) [issues](https://github.com/camunda/zeebe/issues/6314) related to `maxMessageSize` that lead to bad user experience but it's not clear when or even if this will be solved.

__Additional context__

Internal slack discussion: https://camunda.slack.com/archives/C02JLRNQQ05/p1673887887200989

**Comment by nikku** [comment] 2023-01-20 07:32
I suggest that we fix this rather quickly; moving to `ready` to propose.

Why: Because it is a topic that is hard to impossible to root cause without specific internal knowledge. We should in no situation prevent incidents from being created.

**Comment by chillleader** [comment] 2023-02-01 11:56
Implemented in [0.6.0-alpha1](https://github.com/camunda/connector-sdk/releases/tag/0.6.0-alpha1) release.

**Closed by chillleader** 2023-02-01 11:56 UTC
Labels: enhancement, ux
